### ISSUE TITLE
ArduinoJson version 6 now, compile fails.

### ISSUE THREAD

**Issue by badlandz** [SensorsIot/Wi-Fi-Sniffer-as-a-Human-detector#18]
Compiling error, looks like ArduinoJson is on a new, not compatible version. Just reporting it now to you, if I find a fix, I'll follow up.

"StaticJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6"

**Comment by badlandz** [comment]
I made minimal effort to find a way to modify the code, but it seems tricky, much easier to roll back from version 6 to any of the version 5 releases avaliable. Don't know if it helps at all, but at least it compiled now.

**Comment by kettenbach-it** [comment]
It's not hard to upgrade Andreas' Sketch to ArduinoJson 6:

Instead of StaticJsonBuffer use StaticJsonDocument in line 50:

`StaticJsonDocument<JBUFFER> jsonDocument;`

Line 196 is not needed anymre. You can delete it:

`JsonObject& root = jsonBuffer.createObject();`


In line 197 and 198 the arrays for mac and rssi are crated like this:

```
JsonArray mac = jsonDocument.createNestedArray("MAC");
JsonArray rssi = jsonDocument.createNestedArray("RSSI");
```

Line 204, 205, 213 and 214 are like these:

```
mac.add(deviceMac);
rssi.add(aps_known[u].rssi);
```
Before line 224 (upload) you have to insert

`serializeJsonPretty(jsonDocument, jsonString);`
